# Generated by Django 3.0.7 on 2021-03-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/search?q=place+holder+food+image&client=firefox-b-d&tbm=isch&source=iu&ictx=1&fir=KzlEw1u98W7EKM%252C75wDOX_EasD4oM%252C_&vet=1&usg=AI4_-kRYOPWQPGXlQPRLHN-DG2zoFjbpxg&sa=X&ved=2ahUKEwis2LzOocPvAhX3yDgGHU_VC5IQ9QF6BAgLEAE#imgrc=KzlEw1u98W7EKM', max_length=500),
        ),
    ]
